version: '3'
services:
  app:
    image: node
    command: npm start
    working_dir: /usr/local/app
    ports:
      - 8080:8080
      - 8081:8081
    volumes:
      - .:/usr/local/app

  end2end:
    image: cypress/base
    command: npm test
    working_dir: /usr/local/end2end
    volumes:
      - ./end2end:/usr/local/end2end
    depends_on:
      - app
